package cn.xbatis.ddl.auto;

import db.sql.api.DbModel;
import db.sql.api.DbType;
import db.sql.api.IDbType;

/**
 * DDL 方言支持。
 * <p>
 * 收敛不同数据库在类型、自增、注释和 ADD COLUMN 语法上的差异。
 */
public class DDLDialect {

    public String getAutoIncrementSql(IDbType dbType) {
        validateDbType(dbType);
        if (isDm(dbType)) {
            return " IDENTITY(1,1)";
        }
        if (isMysql(dbType)) {
            return " AUTO_INCREMENT";
        }
        if (dbType == DbType.SQL_SERVER) {
            return " IDENTITY(1,1)";
        }
        if (isGauss(dbType)) {
            return "";
        }
        if (isPostgresql(dbType) || dbType == DbType.ORACLE || dbType == DbType.DB2 || dbType == DbType.H2) {
            return " GENERATED BY DEFAULT AS IDENTITY";
        }
        if (isSqlite(dbType)) {
            return " PRIMARY KEY AUTOINCREMENT";
        }
        return " AUTO_INCREMENT";
    }

    public String getAutoIncrementType(IDbType dbType, Class<?> javaType) {
        validateDbType(dbType);
        if (isGauss(dbType)) {
            if (javaType == Long.class || javaType == long.class || javaType == java.math.BigInteger.class) {
                return "BIGSERIAL";
            }
            if (javaType == Integer.class || javaType == int.class) {
                return "SERIAL";
            }
            return "SERIAL";
        }
        if (isDm(dbType)) {
            if (javaType == Long.class || javaType == long.class || javaType == java.math.BigInteger.class) {
                return "BIGINT";
            }
            if (javaType == Integer.class || javaType == int.class) {
                return "INTEGER";
            }
        }
        return null;
    }

    public String getStringType(IDbType dbType, int length) {
        validateDbType(dbType);
        if (isOracle(dbType)) {
            return length > 4000 ? "CLOB" : "VARCHAR2(" + length + ")";
        }
        if (dbType == DbType.SQL_SERVER) {
            return length > 4000 ? "NVARCHAR(MAX)" : "NVARCHAR(" + length + ")";
        }
        if (length > 0) {
            return "VARCHAR(" + length + ")";
        }
        return "VARCHAR(255)";
    }

    public String getIntegerType(IDbType dbType) {
        validateDbType(dbType);
        return isOracle(dbType) ? "NUMBER(10)" : "INTEGER";
    }

    public String getBigIntType(IDbType dbType) {
        validateDbType(dbType);
        return isOracle(dbType) ? "NUMBER(19)" : "BIGINT";
    }

    public String getSmallIntType(IDbType dbType) {
        validateDbType(dbType);
        return isOracle(dbType) ? "NUMBER(5)" : "SMALLINT";
    }

    public String getByteType(IDbType dbType) {
        validateDbType(dbType);
        if (isOracle(dbType)) {
            return "NUMBER(3)";
        }
        if (isPostgresql(dbType)) {
            return "SMALLINT";
        }
        return "TINYINT";
    }

    public String getBooleanType(IDbType dbType) {
        validateDbType(dbType);
        if (dbType == DbType.SQL_SERVER) {
            return "BIT";
        }
        return "BOOLEAN";
    }

    public String getDecimalType(IDbType dbType, int precision, int scale) {
        validateDbType(dbType);
        if (isOracle(dbType)) {
            return "NUMBER(" + precision + "," + scale + ")";
        }
        return "DECIMAL(" + precision + "," + scale + ")";
    }

    public String getBlobType(IDbType dbType) {
        validateDbType(dbType);
        if (isPostgresql(dbType)) {
            return "BYTEA";
        }
        if (dbType == DbType.SQL_SERVER) {
            return "VARBINARY(MAX)";
        }
        return "BLOB";
    }

    public String getTimeType(IDbType dbType) {
        validateDbType(dbType);
        if (isOracle(dbType)) {
            return "TIMESTAMP";
        }
        return "TIME";
    }

    public String getDateTimeType(IDbType dbType) {
        validateDbType(dbType);
        if (isMysql(dbType)) {
            return "DATETIME";
        }
        if (isSqlServer(dbType)) {
            return "DATETIME2";
        }
        return "TIMESTAMP";
    }

    public String getDateTimeWithTimeZoneType(IDbType dbType) {
        validateDbType(dbType);
        if (isMysql(dbType)) {
            return "TIMESTAMP";
        }
        if (isSqlServer(dbType)) {
            return "DATETIMEOFFSET";
        }
        if (dbType == DbType.DB2) {
            return "TIMESTAMP";
        }
        if (dbType == DbType.CLICK_HOUSE) {
            return "DateTime64(3, 'UTC')";
        }
        return "TIMESTAMP WITH TIME ZONE";
    }

    public boolean isMysql(IDbType dbType) {
        validateDbType(dbType);
        return dbType == DbType.MYSQL || dbType == DbType.MARIA_DB || dbType.getDbModel() == DbModel.MYSQL;
    }

    public boolean isPostgresql(IDbType dbType) {
        validateDbType(dbType);
        return dbType == DbType.PGSQL || dbType.getDbModel() == DbModel.PGSQL;
    }

    public boolean isGauss(IDbType dbType) {
        validateDbType(dbType);
        return dbType == DbType.GAUSS;
    }

    public boolean isOracle(IDbType dbType) {
        validateDbType(dbType);
        return dbType == DbType.ORACLE || dbType == DbType.DM || dbType.getDbModel() == DbModel.ORACLE;
    }

    public boolean isDm(IDbType dbType) {
        validateDbType(dbType);
        return dbType == DbType.DM;
    }

    public boolean isSqlServer(IDbType dbType) {
        validateDbType(dbType);
        return dbType == DbType.SQL_SERVER;
    }

    public boolean isSqlite(IDbType dbType) {
        validateDbType(dbType);
        return dbType == DbType.SQLITE;
    }

    public boolean supportsCreateTableIfNotExists(IDbType dbType) {
        validateDbType(dbType);
        return isMysql(dbType)
                || isPostgresql(dbType)
                || dbType == DbType.SQLITE
                || dbType == DbType.H2
                || dbType == DbType.CLICK_HOUSE;
    }

    public boolean supportsCreateSequenceIfNotExists(IDbType dbType) {
        validateDbType(dbType);
        return dbType == DbType.PGSQL;
    }

    public boolean supportsAddColumnKeyword(IDbType dbType) {
        validateDbType(dbType);
        return dbType != DbType.ORACLE && dbType != DbType.DM && dbType != DbType.SQL_SERVER;
    }

    public boolean supportsMultipleAddColumns(IDbType dbType) {
        validateDbType(dbType);
        return !isSqlite(dbType);
    }

    public boolean supportsUniqueConstraint(IDbType dbType) {
        validateDbType(dbType);
        return dbType != DbType.CLICK_HOUSE;
    }

    public boolean supportsInlineUniqueInAddColumn(IDbType dbType) {
        validateDbType(dbType);
        return !isSqlite(dbType);
    }

    public boolean supportsColumnCommentStatement(IDbType dbType) {
        validateDbType(dbType);
        return isPostgresql(dbType) || isOracle(dbType) || isSqlServer(dbType);
    }

    public boolean supportsTableCommentStatement(IDbType dbType) {
        validateDbType(dbType);
        return isPostgresql(dbType)
                || isOracle(dbType)
                || isSqlServer(dbType)
                || dbType == DbType.DB2
                || dbType == DbType.H2;
    }

    public boolean supportsCreateIndex(IDbType dbType) {
        validateDbType(dbType);
        return dbType != DbType.CLICK_HOUSE;
    }

    protected void validateDbType(IDbType dbType) {
        if (dbType == null) {
            throw new NullPointerException("dbType");
        }
        if (dbType == DbType.UNKNOWN) {
            throw new IllegalArgumentException("dbType must be a concrete database type");
        }
    }
}
