package cn.xbatis.ddl.auto;

import cn.xbatis.db.IndexDirection;
import cn.xbatis.db.annotations.*;
import db.sql.api.DbType;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

@Tag("integration")
class DDLAutoPostgresIntegrationTest {

    private static final String TEST_TABLE = "auto_postgres_integration_user";

    private static final String POSTGRES_URL = System.getProperty(
            "postgres.test.url",
            "jdbc:postgresql://127.0.0.1:5432/ddl_test?connectTimeout=2&socketTimeout=5"
    );

    private static final String POSTGRES_ADMIN_URL = System.getProperty(
            "postgres.test.admin.url",
            adminDatabaseUrl(POSTGRES_URL)
    );

    private static final String POSTGRES_USERNAME = System.getProperty("postgres.test.username", "postgres");

    private static final String POSTGRES_PASSWORD = System.getProperty("postgres.test.password", "123456");

    @Test
    void postgresShouldCreateTableAddColumnAndCreateMissingIndexes() throws Exception {
        try (Connection connection = openDatabaseConnectionOrSkip()) {
            dropTestTable(connection);
            try {
                DDLTestPrinter.ddl(DbType.PGSQL)
                        .builder(new DefaultDDLBuilder())
                        .add(PostgresIntegrationUserV1.class)
                        .execute(connection);

                assertTrue(tableExists(connection, TEST_TABLE));
                assertTrue(columnExists(connection, TEST_TABLE, "username"));
                assertTrue(indexExists(connection, TEST_TABLE, "idx_postgres_integration_username"));
                assertFalse(columnExists(connection, TEST_TABLE, "email"));
                assertFalse(indexExists(connection, TEST_TABLE, "idx_postgres_integration_email"));

                assertFalse(columnExists(connection, TEST_TABLE, "email"));

                List<String> updateExecutedSqlList = new java.util.ArrayList<>();
                DDLTestPrinter.ddl(DbType.PGSQL, updateExecutedSqlList)
                        .builder(new DefaultDDLBuilder())
                        .mode(Mode.UPDATE)
                        .add(PostgresIntegrationUserV2.class)
                        .execute(connection);

                assertTrue(updateExecutedSqlList.contains("ALTER TABLE " + TEST_TABLE + " ADD COLUMN email VARCHAR(128);"));
                assertTrue(updateExecutedSqlList.contains("CREATE INDEX idx_postgres_integration_email ON " + TEST_TABLE + " (email);"));
                assertTrue(updateExecutedSqlList.contains("CREATE INDEX idx_postgres_integration_username_created_at ON "
                        + TEST_TABLE + " (username ASC, created_at DESC);"));
                assertTrue(columnExists(connection, TEST_TABLE, "email"));
                assertTrue(indexExists(connection, TEST_TABLE, "idx_postgres_integration_email"));
                assertTrue(indexExists(connection, TEST_TABLE, "idx_postgres_integration_username_created_at"));
                List<String> verifyExecutedSqlList = new java.util.ArrayList<>();
                DDLTestPrinter.ddl(DbType.PGSQL, verifyExecutedSqlList)
                        .builder(new DefaultDDLBuilder())
                        .mode(Mode.UPDATE)
                        .add(PostgresIntegrationUserV2.class)
                        .execute(connection);
                assertTrue(verifyExecutedSqlList.isEmpty(), "Expected no PostgreSQL DDL after update already executed: " + verifyExecutedSqlList);
            } finally {
                dropTestTable(connection);
            }
        }
    }

    @Test
    void postgresShouldCreateIntLongAutoAndManualIdTables() throws Exception {
        try (Connection connection = openDatabaseConnectionOrSkip()) {
            DDLAutoExternalDatabaseIntegrationSupport.assertIntLongAutoAndManualIdFlow(
                    DbType.PGSQL,
                    connection,
                    "id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY",
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY",
                    "id INTEGER NOT NULL PRIMARY KEY",
                    "id BIGINT NOT NULL PRIMARY KEY"
            );
        }
    }

    @Test
    void postgresShouldCreateTableDefinitionComment() throws Exception {
        try (Connection connection = openDatabaseConnectionOrSkip()) {
            DDLAutoExternalDatabaseIntegrationSupport.assertTableDefinitionFlow(
                    DbType.PGSQL,
                    connection,
                    PostgresTableDefinitionIntegrationUser.class,
                    "auto_postgres_table_definition_user",
                    null,
                    "COMMENT ON TABLE auto_postgres_table_definition_user IS 'PostgreSQL表';"
            );
        }
    }

    @Test
    void postgresShouldCreateMultiplePhysicalTablesWithSequenceAndIndexes() throws Exception {
        try (Connection connection = openDatabaseConnectionOrSkip()) {
            DDLAutoExternalDatabaseIntegrationSupport.assertMultiTableSequenceAndIndexFlow(DbType.PGSQL, connection);
        }
    }

    private static Connection openDatabaseConnectionOrSkip() throws SQLException {
        try {
            return DriverManager.getConnection(POSTGRES_URL, POSTGRES_USERNAME, POSTGRES_PASSWORD);
        } catch (SQLException exception) {
            if (isDatabaseMissing(exception)) {
                createDatabaseOrSkip(exception);
                return DriverManager.getConnection(POSTGRES_URL, POSTGRES_USERNAME, POSTGRES_PASSWORD);
            }
            assumeTrue(false, "Skip PostgreSQL integration test, local PostgreSQL is not available: " + exception.getMessage());
            throw exception;
        }
    }

    private static void createDatabaseOrSkip(SQLException missingDatabaseException) throws SQLException {
        String databaseName = databaseName(POSTGRES_URL);
        if (databaseName == null || databaseName.isEmpty()) {
            assumeTrue(false, "Skip PostgreSQL integration test, postgres.test.url has no database name: " + POSTGRES_URL);
            throw missingDatabaseException;
        }
        try (Connection connection = DriverManager.getConnection(POSTGRES_ADMIN_URL, POSTGRES_USERNAME, POSTGRES_PASSWORD)) {
            if (!databaseExists(connection, databaseName)) {
                createDatabase(connection, databaseName);
            }
        } catch (SQLException exception) {
            exception.addSuppressed(missingDatabaseException);
            assumeTrue(false, "Skip PostgreSQL integration test, database " + databaseName
                    + " does not exist and cannot be created through " + POSTGRES_ADMIN_URL + ": " + exception.getMessage());
            throw exception;
        }
    }

    private static boolean isDatabaseMissing(SQLException exception) {
        for (SQLException current = exception; current != null; current = current.getNextException()) {
            if ("3D000".equals(current.getSQLState())) {
                return true;
            }
        }
        return false;
    }

    private static boolean databaseExists(Connection connection, String databaseName) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement("SELECT COUNT(*) FROM pg_database WHERE datname = ?")) {
            statement.setString(1, databaseName);
            return hasRows(statement);
        }
    }

    private static void createDatabase(Connection connection, String databaseName) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("CREATE DATABASE " + quoteIdentifier(databaseName));
        }
    }

    private static String quoteIdentifier(String name) {
        return "\"" + name.replace("\"", "\"\"") + "\"";
    }

    private static String adminDatabaseUrl(String url) {
        return replaceDatabaseName(url, "postgres");
    }

    private static String databaseName(String url) {
        JdbcUrlParts parts = parseJdbcUrl(url);
        return parts.databaseName;
    }

    private static String replaceDatabaseName(String url, String databaseName) {
        JdbcUrlParts parts = parseJdbcUrl(url);
        return parts.prefix + databaseName + parts.query;
    }

    private static JdbcUrlParts parseJdbcUrl(String url) {
        String query = "";
        String urlWithoutQuery = url;
        int queryIndex = url.indexOf('?');
        if (queryIndex >= 0) {
            query = url.substring(queryIndex);
            urlWithoutQuery = url.substring(0, queryIndex);
        }
        String prefix = "jdbc:postgresql://";
        if (urlWithoutQuery.startsWith(prefix)) {
            int databaseStart = urlWithoutQuery.indexOf('/', prefix.length());
            if (databaseStart < 0) {
                return new JdbcUrlParts(urlWithoutQuery + "/", "", query);
            }
            return new JdbcUrlParts(urlWithoutQuery.substring(0, databaseStart + 1),
                    urlWithoutQuery.substring(databaseStart + 1), query);
        }
        prefix = "jdbc:postgresql:";
        if (urlWithoutQuery.startsWith(prefix)) {
            return new JdbcUrlParts(prefix, urlWithoutQuery.substring(prefix.length()), query);
        }
        return new JdbcUrlParts(urlWithoutQuery, "", query);
    }

    static class JdbcUrlParts {

        private final String prefix;

        private final String databaseName;

        private final String query;

        JdbcUrlParts(String prefix, String databaseName, String query) {
            this.prefix = prefix;
            this.databaseName = databaseName;
            this.query = query;
        }
    }

    private static void dropTestTable(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS " + TEST_TABLE);
        }
    }

    private static boolean tableExists(Connection connection, String tableName) throws SQLException {
        String sql = "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, tableName);
            return hasRows(statement);
        }
    }

    private static boolean columnExists(Connection connection, String tableName, String columnName) throws SQLException {
        String sql = "SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = ? AND column_name = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, tableName);
            statement.setString(2, columnName);
            return hasRows(statement);
        }
    }

    private static boolean indexExists(Connection connection, String tableName, String indexName) throws SQLException {
        String sql = "SELECT COUNT(*) FROM pg_indexes WHERE schemaname = current_schema() AND tablename = ? AND indexname = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, tableName);
            statement.setString(2, indexName);
            return hasRows(statement);
        }
    }

    private static boolean hasRows(PreparedStatement statement) throws SQLException {
        try (ResultSet resultSet = statement.executeQuery()) {
            return resultSet.next() && resultSet.getInt(1) > 0;
        }
    }

    @Table("auto_postgres_integration_user")
    @Index(name = "idx_postgres_integration_username", fields = @IndexField(name = "username"))
    static class PostgresIntegrationUserV1 {

        @TableId
        private Long id;

        @ColumnDefinition(length = 64, nullable = false, comment = "用户名")
        private String username;

        @ColumnDefinition(precision = 12, scale = 2, defaultValue = "0")
        private BigDecimal balance;

        private LocalDateTime createdAt;
    }

    @Table("auto_postgres_integration_user")
    @Indexs({
            @Index(name = "idx_postgres_integration_username", fields = @IndexField(name = "username")),
            @Index(name = "idx_postgres_integration_email", fields = @IndexField(name = "email")),
            @Index(name = "idx_postgres_integration_username_created_at", fields = {
                    @IndexField(name = "username", direction = IndexDirection.ASC),
                    @IndexField(name = "createdAt", direction = IndexDirection.DESC)
            })
    })
    static class PostgresIntegrationUserV2 {

        @TableId
        private Long id;

        @ColumnDefinition(length = 64, nullable = false, comment = "用户名")
        private String username;

        @ColumnDefinition(precision = 12, scale = 2, defaultValue = "0")
        private BigDecimal balance;

        private LocalDateTime createdAt;

        @ColumnDefinition(length = 128)
        private String email;
    }

    @Table("auto_postgres_table_definition_user")
    @TableDefinition(comment = "PostgreSQL表")
    static class PostgresTableDefinitionIntegrationUser {

        @TableId
        private Long id;

        @ColumnDefinition(length = 64, nullable = false)
        private String username;
    }
}
